name: flutter_testing
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/1.jpg
    - images/2.jpg
    - images/3.jpg
    - images/4.jpg
    - images/5.jpg
    - images/6.jpg
    - images/7.jpg
    - images/8.jpg
    - images/9.jpg
    - images/10.jpg
    - images/11.jpg
    - images/12.jpg
    - images/13.jpg
    - images/14.jpg
    - images/15.jpg
    - images/16.jpg
    - images/17.jpg
    - images/18.jpg
